version: "3.8"

# Base Template (YAML Anchor)
x-superbot-base: &base
  image: ${IMAGE_TAG:-superbot:latest}
  restart: unless-stopped
  network_mode: "host"

services:
  # --------------------------------------------------------
  # PROFILE: GPU
  # --------------------------------------------------------
  superbot-gpu:
    <<: *base
    container_name: superbot_engine_gpu
    profiles: ["gpu"]
    volumes:
      - ./${CONFIG_PATH}:/app/config/superbot_config.json:ro
      - ${LORAS_PATH:-./loras}:/loras:ro
      - ./build/entrypoint.sh:/app/entrypoint.sh:ro  # <-- HACK LOCAL 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # --------------------------------------------------------
  # PROFILE: CPU
  # --------------------------------------------------------
  superbot-cpu:
    <<: *base
    container_name: superbot_engine_cpu
    profiles: ["cpu"]
    environment:
      - LD_LIBRARY_PATH=/usr/lib:/usr/local/cuda/lib64/stubs
    volumes:
      - ./${CONFIG_PATH}:/app/config/superbot_config.json:ro
      - ${LORAS_PATH:-./loras}:/loras:ro
      - ./build/entrypoint.sh:/app/entrypoint.sh:ro  # <-- HACK LOCAL 